Develop
nnslvp/lazy-bison-landing pull request #23
Opened 2023-11-28 12:29 UTC by AndrewMatsiash

2023-12-06 15:56 UTC, nnslvp commented on jekyll/_blogs/2023-11-28-blog.md
> +hashtags: '#eCommerce #real estate'
Это категории, по ним мы должны мочь фильтровать контент

2023-12-13 18:28 UTC, nnslvp requested changes
Я побыстрому пробежался, сделай плз себе код ревью.
Вот пример .gitignore: https://github.com/github/gitignore/blob/main/community/Golang/Hugo.gitignore

2023-12-13 18:28 UTC, nnslvp commented on hugo/assets/js/sliders.js
> +// const sliders = document.querySelectorAll('.swiper')
?

2023-12-13 18:28 UTC, nnslvp commented on .DS_Store
Думаю надо добавить в .gitignore

2023-12-13 18:28 UTC, nnslvp commented on hugo/.hugo_build.lock
Что это за файл? Мб в гитигнор?

2023-12-13 18:28 UTC, nnslvp commented on hugo/archetypes/blogs.md
> +layout: blog
В архитипах по идее должен быть пример контента а не готовый пост, так?

2023-12-13 18:28 UTC, nnslvp commented on hugo/archetypes/cases.md
> +title: 'Logistics in Motion: Overcoming Challenges and Achieving Excellence'
Архитипы в Hugo представляют собой шаблоны для создания новых контент-файлов. Когда вы создаете новую страницу с помощью команды `hugo new`, Hugo использует архитипы для автоматического заполнения Front Matter (метаданных в заголовке файла) нового контент-файла.

### Для чего нужны архитипы?

1. **Стандартизация Front Matter:** Архитипы позволяют вам определить стандартный набор метаданных для различных типов контента. Например, для всех постов блога можно автоматически добавлять определенные поля, такие как `date`, `title`, `author` и т.д.

2. **Ускорение рабочего процесса:** Использование архитипов упрощает и ускоряет процесс создания нового контента, автоматически добавляя необходимые метаданные.

3. **Согласованность:** Архитипы обеспечивают единообразие структуры контента на вашем сайте.

### Что писать в архитипах?

В архитипе вы обычно указываете базовую структуру Front Matter для новых файлов определенного типа. Например, для поста в блоге архитип может выглядеть так:

```yaml
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
draft: true
author: "Имя автора"
---
```

Здесь:

- `title`: Заголовок поста, генерируемый автоматически из имени файла, но вы можете его изменить.
- `date`: Дата создания поста, устанавливается в момент создания файла.
- `draft`: Определяет, является ли страница черновиком.
- `author`: Поле для имени автора.

Вы можете настроить архитип под свои нужды, добавляя или убирая поля в зависимости от того, какие данные важны для вашего сайта и типов контента.

### Как создать архитип

Чтобы создать архитип, просто создайте файл с расширением `.md` в папке `archetypes` вашего проекта Hugo. Имя файла должно соответствовать типу контента. Например, `post.md` для постов блога.

2023-12-13 18:28 UTC, nnslvp commented on hugo/archetypes/default.md
Этот файл все еще нужен?

2023-12-13 18:28 UTC, nnslvp commented on hugo/assets/js/popups.js
> +
Пустой файл?

2023-12-13 18:28 UTC, nnslvp commented on hugo/content/blogs/2023-11-30-blog.md
> +blog_categories: ['real estate']
Не похоже на реальный пост

2023-12-13 18:28 UTC, nnslvp commented on hugo/content/blogs/2023-12-06-automating-deployments-blog.md
> +blog_categories: ['real estate']
Не похоже на реальную категорию

2023-12-13 18:28 UTC, nnslvp commented on hugo/content/blogs/_index.md
> +title: 'Blogs'
```suggestion
title: 'Blog'
```

2023-12-13 18:28 UTC, nnslvp commented on hugo/content/cases/_index.md
> +title: 'Сases'
Это точно нужно?

2023-12-13 18:28 UTC, nnslvp commented on hugo/hugo.toml
> +
Лишние пустые строки

2023-12-13 18:28 UTC, nnslvp commented on hugo/layouts/partials/navigation-path.html
> +
Пустые строки

2023-12-13 18:28 UTC, nnslvp commented on hugo/resources/_gen/assets/scss/sass/main.scss_5481928335aee5e714c50847675a4f4e.content
> +@charset "UTF-8";/*!normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css*/html{line-height:1.15;-webkit-text-size-adjust:100%}fdfdfdf body{margin:0}main{display:block}h1{font-size:2e
Подозреваю что этот файл и подобные должны быть в .gitignore

2023-12-13 18:29 UTC, nnslvp commented
Конфликты

2023-12-13 18:33 UTC, nnslvp commented
<img width="405" alt="image" src="https://github.com/nnslvp/lazy-bison-landing/assets/65916399/3523d958-68fd-42d6-a37c-23e58de01ba3">

странная структура, вынеси все в корень

2023-12-13 18:36 UTC, nnslvp commented
Кейсы в хроме странно отображаются 
<img width="2165" alt="image" src="https://github.com/nnslvp/lazy-bison-landing/assets/65916399/9ebaf891-9f31-4f27-8eff-cbc015be2804">

2023-12-14 08:53 UTC, AndrewMatsiash commented
> Кейсы в хроме странно отображаются <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/65916399/290293615-9ebaf891-9f31-4f27-8eff-cbc015be2804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDM5MjEsIm5iZiI6MTcwMjU0MzYyMSwicGF0aCI6Ii82NTkxNjM5OS8yOTAyOTM2MTUtOWViYWY4OTEtOWYzMS00ZjI3LThlZmYtY2JjMDE1YmUyODA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA4NDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZTUwY2Y1YzNjNjAyMjJiZTljN2RmYTc3MjhmYWNmOTBmMTU2YTkwMzFiODQ1Y2JjYzNhNTNlNmVlOWFhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B995HowOUqh7sWVz5PFwMxdyQWjLU-G7ihhDiu-8VRU">

2023-12-14 12:08 UTC, AndrewMatsiash commented
@nnslvp 
<img width="1198" alt="Снимок экрана 2023-12-14 в 11 51 41" src="https://github.com/nnslvp/lazy-bison-landing/assets/74107101/8870c83b-5b7a-4863-8a8c-66cd0a807333">
<img width="1749" alt="Снимок экрана 2023-12-14 в 11 52 13" src="https://github.com/nnslvp/lazy-bison-landing/assets/74107101/cd57d7d1-9052-41b1-9fff-f645878435ae">
<img width="1260" alt="Снимок экрана 2023-12-14 в 11 52 26" src="https://github.com/nnslvp/lazy-bison-landing/assets/74107101/0cf9574c-4a96-4590-94e7-4d9887e94789">
<img width="1583" alt="Снимок экрана 2023-12-14 в 11 52 52" src="https://github.com/nnslvp/lazy-bison-landing/assets/74107101/796db888-a75e-4453-855b-d50239e8e377">
где ты баги поймал с кейсами? я чекаю в трех браузерах все ок вроде

2024-01-05 13:30 UTC, merged