Feature/new feature add admin
nnslvp/lazy-bison-landing pull request #42
Opened 2024-01-30 14:51 UTC by AndrewMatsiash

я админку сейчас запускаю локально,так как я не могу сделать по другому,так не имею права доступа к репозиторию,чтобы подключить админку с помощью github.Cделаем это позже. Сейчас чтобы потестить админку нужно в корне проекта запустить npx decap-server потом в Hugo serve и по например http://localhost:1313/admin будет дуступна админка.
 Сейчас можно создать
- Case
- Post
- Testiomonials

2024-02-02 12:46 UTC, nnslvp commented on assets/js/main.js
> +	if (tabsTable && tabsTable.length >= 2) {
Для чего нам надо через JS добавлять какие-то стили?

2024-02-05 14:57 UTC, AndrewMatsiash commented on assets/js/main.js
> +	if (tabsTable && tabsTable.length >= 2) {
мы таблицу добавляем через markdown,она отабражается,с помощью js я вешаю класс для акивного таба и таблицы,у нас же там табы на 768 появляются,класс тоглится и колонки появляются и исчезают, а раньше таблица была разбита на переменные и классы уже были на ней,но так очень не удобно для админки ведь колонок может быть много,как и ячеек

2024-02-05 15:05 UTC, nnslvp commented
конфликты

2024-02-05 15:06 UTC, nnslvp commented on assets/js/main.js
> +	if (tabsTable && tabsTable.length >= 2) {
То есть у нас нет возможности генерит таблицу сращу с нужными классами?

2024-02-05 15:11 UTC, AndrewMatsiash commented on assets/js/main.js
> +	if (tabsTable && tabsTable.length >= 2) {
Если только,делать это самому в мардауне каждый раз при создании таблицы,но это не удобно тем,что если забудешь,то все,стили поедут.Либо в js привязываться не к классам,а к тегам  на странице.

2024-02-05 15:18 UTC, AndrewMatsiash commented on assets/js/main.js
> +	if (tabsTable && tabsTable.length >= 2) {
Конечно можно еще,сделать это на чистом css

2024-02-05 15:19 UTC, AndrewMatsiash commented on assets/js/main.js
> +	if (tabsTable && tabsTable.length >= 2) {
и привязаться  тоже  к тегам

2024-02-06 13:03 UTC, nnslvp approved these changes

2024-02-06 14:37 UTC, nnslvp requested changes
Пример не работает

2024-02-07 16:25 UTC, nnslvp commented
Ребейзни все и перепроверь на своем репо плз

2024-02-15 16:51 UTC, nnslvp approved these changes

2024-02-16 09:37 UTC, merged