feat: add content for case expense elegance
nnslvp/lazy-bison-landing pull request #53
Opened 2024-02-20 12:38 UTC by AndrewMatsiash

2024-02-20 13:22 UTC, nnslvp requested changes

2024-02-20 13:22 UTC, nnslvp commented on layouts/cases/single.html
> +        {{ $logisticsImprovements := .Params.value_driven_results.logisticsImprovements }}
Почему тебе приходится писать код с упоминанием контента? Здесь явно что-то не так, шаблон должен быть универсальным и в ходе ничего не должно быть про логистику

2024-02-20 13:22 UTC, nnslvp commented on content/cases/2023-12-06-expense-elegance-case.md
> +  subtitle:
Почему не через админку?

2024-02-20 13:28 UTC, AndrewMatsiash commented on layouts/cases/single.html
> +        {{ $logisticsImprovements := .Params.value_driven_results.logisticsImprovements }}
а что значит упоминание контента?Это универсальный шаблон для секции,которая отрисовывает контент,в этом случае список улучшений,в админке добавляешь их и они в цикле отрисовываются в списках.Переменную переименую в просто  в Improvements

2024-02-20 13:29 UTC, AndrewMatsiash commented on content/cases/2023-12-06-expense-elegance-case.md
> +  subtitle:
у меня же нет прав,я протестил все у себя и добавлял через админку тестовую

2024-02-20 13:32 UTC, AndrewMatsiash commented on layouts/cases/single.html
> +        {{ $logisticsImprovements := .Params.value_driven_results.logisticsImprovements }}
.Params - лежат все данные для страницы
value_driven_results - все данные для секции value driven resultslogisticsImprovements - соответсвенно список для этой секции

2024-02-20 16:46 UTC, nnslvp commented on layouts/cases/single.html
> +        {{ $logisticsImprovements := .Params.value_driven_results.logisticsImprovements }}
Ничего про logistics в коде быть не должно, для чего оно тут?

2024-02-20 16:47 UTC, nnslvp commented on content/cases/2023-12-06-expense-elegance-case.md
> +  subtitle:
Мне кажется права есть, но ссылку я действительно не кидал: https://lazy-bison-admin.netlify.app

2024-02-21 08:10 UTC, AndrewMatsiash commented on layouts/cases/single.html
> +        {{ $logisticsImprovements := .Params.value_driven_results.logisticsImprovements }}
я убрал это название,не корректно назвал переменную,теперь  это  results

2024-02-21 08:15 UTC, AndrewMatsiash commented on content/cases/2023-12-06-expense-elegance-case.md
> +  subtitle:
тогда уже следущие нужно добавлять через админку,так как в этом пулл реквесте код для отрисовки в разметке и если убрать код из кейсов  и слить то в кейсах ничего не отрисуется,пока я не добавлю через админку и получается на сайте на время пропадут элементы,что не хорошо

2024-02-21 14:03 UTC, nnslvp approved these changes

2024-02-21 15:03 UTC, merged